name: Docker Action Demo

on:
  push:
  workflow_dispatch:

jobs:
  test-docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Docker Message Action
        id: docker_message
        uses: ./.github/actions/docker-action
        with:
          message: "Hello World"

      - name: Print output from Docker Action
        run: echo "Step output final_message=${{ steps.docker_message.outputs.final_message }}"
